import { ActionIcon, Alert, Badge, Button, Divider, Group, Menu, MultiSelect, NumberInput, Paper, SegmentedControl, Select, Slider, Stack, Tabs, Text, TextInput, Textarea } from '@mantine/core'
import { useState, useEffect, useCallback, useMemo, useRef } from 'react'
import { IconChecklist, IconCheck, IconPercentage20 } from '@tabler/icons-react'
import { STATUS_LABELS, STATUS_STYLES, SCOPE_COLORS } from '../config'
import { getLevelStatus } from '../utils/nodeStatus'
import { UNASSIGNED_SEGMENT_ID } from '../utils/layoutShared'
import { commitInspectorDrafts } from '../utils/inspectorCommit'
import { EFFORT_SIZE_LABELS, BENEFIT_SIZE_LABELS, EFFORT_SIZES, BENEFIT_SIZES } from '../utils/effortBenefit'
import { MarkdownField } from './MarkdownField'
import { Tooltip } from '../tooltip'
import { generateUniqueShortName, getDefaultLevelLabel, getExplicitLevelLabel, getLevelDisplayLabel, isAutoGeneratedShortName } from '../utils/treeData'

const TablerInfoCircleIcon = ({ size = 16 }) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    aria-hidden="true"
  >
    <path d="M12 9h.01" />
    <path d="M11 12h1v4h1" />
    <path d="M12 3a9 9 0 1 0 0 18a9 9 0 0 0 0 -18" />
  </svg>
)

const TablerAdjustmentsIcon = ({ size = 16 }) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    aria-hidden="true"
  >
    <path d="M4 6h16" />
    <path d="M7 12h10" />
    <path d="M10 18h4" />
  </svg>
)

const TablerCirclePlusIcon = ({ size = 18 }) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    aria-hidden="true"
  >
    <path d="M12 9v6" />
    <path d="M9 12h6" />
    <path d="M12 3a9 9 0 1 0 0 18a9 9 0 0 0 0 -18" />
  </svg>
)

const TablerRefreshIcon = ({ size = 16 }) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    aria-hidden="true"
  >
    <path d="M20 11a8.1 8.1 0 0 0 -15.5 -2m-.5 -4v4h4" />
    <path d="M4 13a8.1 8.1 0 0 0 15.5 2m.5 4v-4h-4" />
  </svg>
)

const TablerPercentIcon = ({ size = 16 }) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    aria-hidden="true"
  >
    <path d="M19 5L5 19" />
    <circle cx="6.5" cy="6.5" r="2.5" />
    <circle cx="17.5" cy="17.5" r="2.5" />
  </svg>
)

const withAlpha = (color, alpha) => {
  if (!color || typeof color !== 'string') return `rgba(148, 163, 184, ${alpha})`

  if (color.startsWith('#')) {
    const hex = color.slice(1)
    const normalized = hex.length === 3 ? hex.split('').map((c) => c + c).join('') : hex
    if (/^[0-9a-fA-F]{6}$/.test(normalized)) {
      const r = parseInt(normalized.slice(0, 2), 16)
      const g = parseInt(normalized.slice(2, 4), 16)
      const b = parseInt(normalized.slice(4, 6), 16)
      return `rgba(${r}, ${g}, ${b}, ${alpha})`
    }
  }

  const rgbMatch = color.match(/^rgba?\(([^)]+)\)$/i)
  if (rgbMatch) {
    const [r = '148', g = '163', b = '184'] = rgbMatch[1].split(',').map((part) => part.trim())
    return `rgba(${r}, ${g}, ${b}, ${alpha})`
  }

  return color
}

const getStatusTextColor = (statusKey, statusStyle) => {
  if (statusKey === 'done') return '#0f172a'
  if (statusKey === 'hidden' || statusKey === 'later' || statusKey === 'someday') return '#e2e8f0'
  return statusStyle?.textColor ?? '#ffffff'
}

const STATUS_OPTIONS = [
  { value: 'done', label: STATUS_LABELS.done },
  { value: 'now', label: STATUS_LABELS.now },
  { value: 'next', label: STATUS_LABELS.next },
  { value: 'later', label: STATUS_LABELS.later },
  { value: 'someday', label: STATUS_LABELS.someday },
  { value: 'hidden', label: STATUS_LABELS.hidden },
].map((option) => {
  const statusStyle = STATUS_STYLES[option.value] ?? STATUS_STYLES.later
  return {
    ...option,
    label: (
      <span
        className={`skill-panel__status-badge skill-panel__status-badge--${option.value}`}
        style={{
          '--status-band': statusStyle.ringBand,
          '--status-soft': withAlpha(statusStyle.ringBand, 0.22),
          '--status-border': withAlpha(statusStyle.ringBand, 0.58),
          '--status-text': getStatusTextColor(option.value, statusStyle),
        }}
      >
        {option.label}
      </span>
    ),
  }
})

const BULK_STATUS_OPTIONS = [
  { value: 'done', label: STATUS_LABELS.done },
  { value: 'now', label: STATUS_LABELS.now },
  { value: 'next', label: STATUS_LABELS.next },
  { value: 'later', label: STATUS_LABELS.later },
  { value: 'someday', label: STATUS_LABELS.someday },
  { value: 'hidden', label: STATUS_LABELS.hidden },
]


const dependencyScopeChipStyle = {
  borderRadius: 999,
  border: '1px solid rgba(148, 163, 184, 0.45)',
  padding: '1px 7px',
  fontSize: '0.68rem',
  lineHeight: 1.5,
  display: 'inline-flex',
  alignItems: 'center',
}

const MAX_SCOPE_CHIPS_PER_ENTRY = 4

const formatInspectorSizeLabel = (label) => (label === 'Unclear' ? '?' : label)
const truncateLevelTabName = (label, maxChars = 6) => {
  const trimmed = String(label ?? '').trim()
  return trimmed.length > maxChars ? `${trimmed.slice(0, maxChars)}...` : trimmed
}

export const getLevelDragInsertPosition = (sourceId, targetId, event, levels) => {
  if (!sourceId || !targetId || sourceId === targetId) {
    return null
  }

  const sourceIndex = levels.findIndex((level) => level.id === sourceId)
  const targetIndex = levels.findIndex((level) => level.id === targetId)

  if (sourceIndex < 0 || targetIndex < 0 || sourceIndex === targetIndex) {
    return null
  }

  const rect = event.currentTarget.getBoundingClientRect()
  const insertPosition = event.clientX < rect.left + rect.width / 2 ? 'before' : 'after'
  const nextIndex = insertPosition === 'after'
    ? (sourceIndex < targetIndex ? targetIndex : targetIndex + 1)
    : (sourceIndex < targetIndex ? targetIndex - 1 : targetIndex)

  return nextIndex === sourceIndex ? null : insertPosition
}

const EFFORT_MARKS = EFFORT_SIZES.map((s, i) => ({ value: i, label: formatInspectorSizeLabel(EFFORT_SIZE_LABELS[s]) }))
const BENEFIT_MARKS = BENEFIT_SIZES.map((s, i) => ({ value: i, label: formatInspectorSizeLabel(BENEFIT_SIZE_LABELS[s]) }))

const DiscreteInspectorSlider = ({ sizes, labels, value, marks, onCommit }) => {
  const [draftIndex, setDraftIndex] = useState(Math.max(0, sizes.indexOf(value ?? sizes[0])))

  useEffect(() => {
    setDraftIndex(Math.max(0, sizes.indexOf(value ?? sizes[0])))
  }, [sizes, value])

  return (
    <Slider
      min={0}
      max={sizes.length - 1}
      step={1}
      value={draftIndex}
      onChange={setDraftIndex}
      onChangeEnd={(idx) => onCommit?.(sizes[idx])}
      marks={marks}
      label={(idx) => formatInspectorSizeLabel(labels[sizes[idx]])}
      size="xs"
      mb={28}
      classNames={{ markLabel: 'mantine-dark-label' }}
    />
  )
}

export function InspectorPanel({
  selectedNode,
  selectedNodeIds,
  roadmapData,
  currentLevel,
  selectedProgressLevelId,
  onClose,
  onLabelChange,
  onShortNameChange,
  onStatusChange,
  onOpenPointsChange,
  onOpenPointsLabelChange,
  onOpenPointTagChange,
  onReleaseNoteChange,
  onLevelLabelChange,
  onScopeIdsChange,
  scopeOptions,
  onCreateScope,
  onRenameScope,
  onDeleteScope,
  onSetScopeColor,
  onCreateSegment,
  onRenameSegment,
  onDeleteSegment,
  onSelectProgressLevel,
  onAddProgressLevel,
  onDeleteProgressLevel,
  onReorderProgressLevel,
  onLevelChange,
  levelOptions,
  segmentOptions,
  parentOptions,
  selectedParentId,
  levelDependencyOptions,
  onLevelAdditionalDependenciesChange,
  dependencyRequires = [],
  dependencyEnables = [],
  validationMessage,
  onParentChange,
  onSegmentChange,
  onDeleteNodeOnly,
  onDeleteNodeBranch,
  onFocusNode,
  onSelectAllNodes,
  onInspectorCommit,
  onEffortChange,
  onBenefitChange,
  selectedReleaseId = null,
}) {
  const [scopeManagerOpen, setScopeManagerOpen] = useState(false)
  const [scopeDraft, setScopeDraft] = useState('')
  const [scopeError, setScopeError] = useState(null)
  const [editingScopeId, setEditingScopeId] = useState(null)
  const [editingScopeLabel, setEditingScopeLabel] = useState('')
  const [colorPickerOpenId, setColorPickerOpenId] = useState(null)
  const [nameDraft, setNameDraft] = useState(selectedNode?.label ?? '')
  const [shortNameDraft, setShortNameDraft] = useState(selectedNode?.shortName ?? '')
  const [releaseNoteDraft, setReleaseNoteDraft] = useState(
    Array.isArray(selectedNode?.levels) && selectedNode.levels[0] ? (selectedNode.levels[0].releaseNote ?? '') : ''
  )
  const nameDraftRef = useRef(nameDraft)
  const shortNameDraftRef = useRef(shortNameDraft)
  const releaseNoteDraftRef = useRef(releaseNoteDraft)
  const committedNameRef = useRef(selectedNode?.label ?? '')
  const committedShortNameRef = useRef(selectedNode?.shortName ?? '')
  const committedReleaseNoteRef = useRef(
    Array.isArray(selectedNode?.levels) && selectedNode.levels[0] ? (selectedNode.levels[0].releaseNote ?? '') : ''
  )
  const [saveToast, setSaveToast] = useState({ visible: false, message: '' })
  const [segmentManagerOpen, setSegmentManagerOpen] = useState(false)
  const [segmentDraft, setSegmentDraft] = useState('')
  const [segmentError, setSegmentError] = useState(null)
  const [editingSegmentId, setEditingSegmentId] = useState(null)
  const [editingSegmentLabel, setEditingSegmentLabel] = useState('')
  const [levelLabelDrafts, setLevelLabelDrafts] = useState({})
  const [isTitleEditing, setIsTitleEditing] = useState(false)
  const [draggedLevelId, setDraggedLevelId] = useState(null)
  const [dragOverLevelId, setDragOverLevelId] = useState(null)
  const [dragInsertPosition, setDragInsertPosition] = useState(null)
  const headerNameInputRef = useRef(null)
  const levelLabelDraftsRef = useRef({})

  useEffect(() => {
    const nextName = selectedNode?.label ?? ''
    const nextShortName = selectedNode?.shortName ?? ''
    const nextReleaseNote = Array.isArray(selectedNode?.levels) && selectedNode.levels[0] ? (selectedNode.levels[0].releaseNote ?? '') : ''

    committedNameRef.current = nextName
    committedShortNameRef.current = nextShortName
    committedReleaseNoteRef.current = nextReleaseNote
    nameDraftRef.current = nextName
    shortNameDraftRef.current = nextShortName
    releaseNoteDraftRef.current = nextReleaseNote

    setNameDraft(nextName)
    setShortNameDraft(nextShortName)
    setReleaseNoteDraft(nextReleaseNote)
    const nextLevelDrafts = Object.fromEntries(
      (selectedNode?.levels ?? []).map((level) => [level.id, getExplicitLevelLabel(level.label)]),
    )
    levelLabelDraftsRef.current = nextLevelDrafts
    setLevelLabelDrafts(nextLevelDrafts)
    setIsTitleEditing(false)
  }, [selectedNode])

  useEffect(() => {
    if (!isTitleEditing) {
      return
    }

    headerNameInputRef.current?.focus()
    headerNameInputRef.current?.select?.()
  }, [isTitleEditing])

  const syncGeneratedShortNameDraft = useCallback((nextName, currentLabel = nameDraftRef.current, currentShortName = shortNameDraftRef.current) => {
    if (!selectedNode || !isAutoGeneratedShortName(currentShortName, currentLabel)) {
      return
    }

    const nextShortName = generateUniqueShortName(roadmapData, selectedNode.id, nextName)
    shortNameDraftRef.current = nextShortName
    setShortNameDraft(nextShortName)
  }, [roadmapData, selectedNode])

  const handleGenerateShortName = useCallback(() => {
    if (!selectedNode) {
      return
    }

    const nextShortName = generateUniqueShortName(roadmapData, selectedNode.id, nameDraftRef.current || selectedNode.label)
    shortNameDraftRef.current = nextShortName
    committedShortNameRef.current = nextShortName
    setShortNameDraft(nextShortName)
    onShortNameChange?.(nextShortName, selectedNode.id)
  }, [onShortNameChange, roadmapData, selectedNode])

  const commitCurrentDrafts = useCallback((showToast = false, commitSource = 'explicit') => {
    if (!selectedNode) {
      return { nameCommitted: false, shortNameCommitted: false, releaseNoteCommitted: false }
    }

    const commitResult = commitInspectorDrafts({
      nameDraft: nameDraftRef.current,
      currentName: committedNameRef.current,
      onNameChange: (nextName) => {
        committedNameRef.current = nextName
        onLabelChange?.(nextName)
      },
      shortNameDraft: shortNameDraftRef.current,
      currentShortName: committedShortNameRef.current,
      onShortNameChange: (nextShortName) => {
        committedShortNameRef.current = nextShortName
        onShortNameChange?.(nextShortName, selectedNode.id)
      },
      releaseNoteDraft: releaseNoteDraftRef.current,
      currentReleaseNote: committedReleaseNoteRef.current,
      onReleaseNoteChange: (nextReleaseNote) => {
        committedReleaseNoteRef.current = nextReleaseNote
        onReleaseNoteChange?.(nextReleaseNote)
      },
    })

    if (showToast && commitResult.nameCommitted) {
      setSaveToast({ visible: true, message: 'Name gespeichert' })
      setTimeout(() => setSaveToast({ visible: false, message: '' }), 1400)
      try {
        window.dispatchEvent(new CustomEvent('roadmap-skilltree.toast', { detail: { type: 'success', message: 'Name gespeichert' } }))
      } catch {
        // ignore
      }
    }

    if (showToast && commitResult.shortNameCommitted) {
      try {
        window.dispatchEvent(new CustomEvent('roadmap-skilltree.toast', { detail: { type: 'success', message: 'Shortname saved' } }))
      } catch {
        // ignore if window not available
      }

      try {
        const enteredShortName = String(shortNameDraftRef.current ?? '').trim()
        if (enteredShortName && enteredShortName.length > 3) {
          window.dispatchEvent(new CustomEvent('roadmap-skilltree.toast', { detail: { type: 'warning', message: 'Shortname longer than 3 characters (warning only)' } }))
        }
      } catch {
        // ignore
      }
    }

    if (showToast && commitResult.releaseNoteCommitted) {
      setSaveToast({ visible: true, message: 'Release Note gespeichert' })
      setTimeout(() => setSaveToast({ visible: false, message: '' }), 1400)
      try {
        window.dispatchEvent(new CustomEvent('roadmap-skilltree.toast', { detail: { type: 'success', message: 'Release Note gespeichert' } }))
      } catch {
        // ignore
      }
    }

    onInspectorCommit?.(commitResult, commitSource)

    return commitResult
  }, [onInspectorCommit, onLabelChange, onReleaseNoteChange, onShortNameChange, selectedNode])

  useEffect(() => {
    return () => {
      commitCurrentDrafts(false, 'selection-change')
    }
  }, [commitCurrentDrafts])

  useEffect(() => {
    const handleCommitTextDrafts = () => {
      commitCurrentDrafts(true, 'shortcut')
    }

    window.addEventListener('roadmap-skilltree.commit-text-drafts', handleCommitTextDrafts)
    return () => window.removeEventListener('roadmap-skilltree.commit-text-drafts', handleCommitTextDrafts)
  }, [commitCurrentDrafts])

  const handleStartTitleEdit = useCallback(() => {
    if (!selectedNode) return
    setIsTitleEditing(true)
  }, [selectedNode])

  const handleCancelTitleEdit = useCallback(() => {
    const resetName = committedNameRef.current ?? ''
    const resetShortName = committedShortNameRef.current ?? ''

    nameDraftRef.current = resetName
    shortNameDraftRef.current = resetShortName
    setNameDraft(resetName)
    setShortNameDraft(resetShortName)
    setIsTitleEditing(false)
  }, [])

  const handleSaveTitleEdit = useCallback(() => {
    commitCurrentDrafts(true, 'explicit')
    setIsTitleEditing(false)
  }, [commitCurrentDrafts])

  const handleTitleEditKeyDown = useCallback((event) => {
    if (event.key === 'Enter') {
      event.preventDefault()
      handleSaveTitleEdit()
      return
    }

    if (event.key === 'Escape') {
      event.preventDefault()
      handleCancelTitleEdit()
    }
  }, [handleCancelTitleEdit, handleSaveTitleEdit])

  const handleScopeIdsChange = useCallback((nextScopeIds) => {
    const levels = Array.isArray(selectedNode?.levels) ? selectedNode.levels : []
    const activeId = selectedProgressLevelId ?? (levels[0] && levels[0].id)
    const activeLevel = levels.find((l) => l.id === activeId) ?? levels[0] ?? null
    const prevScopeIds = Array.isArray(activeLevel?.scopeIds) ? activeLevel.scopeIds : []

    onScopeIdsChange?.(nextScopeIds)

    try {
      const traceKey = 'roadmap-skilltree.e2e.scopeTrace'
      const traceEnabled = localStorage.getItem('roadmap-skilltree.e2e.traceEnabled') === '1'
      if (traceEnabled) {
        const raw = localStorage.getItem(traceKey)
        const trace = raw ? JSON.parse(raw) : []
        // include a compact node snapshot so immediate E2E dumps capture
        // the node state at the moment of the scope assignment
        const nodeSnapshot = {
          id: selectedNode.id,
          label: selectedNode.label,
          shortName: selectedNode.shortName ?? null,
          segmentId: selectedNode.segmentId ?? null,
          parentId: selectedNode.parentId ?? null,
          levels: Array.isArray(selectedNode.levels)
            ? selectedNode.levels.map((l) => ({ id: l.id, scopeIds: Array.isArray(l.scopeIds) ? l.scopeIds : [] }))
            : [],
        }

        trace.push({
          ts: Date.now(),
          nodeId: selectedNode.id,
          shortName: selectedNode.shortName ?? null,
          prev: prevScopeIds,
          next: nextScopeIds,
          nodeSnapshot,
        })

        // Cap trace to avoid unbounded localStorage growth.
        const MAX_SCOPE_TRACE_ENTRIES = 200
        if (trace.length > MAX_SCOPE_TRACE_ENTRIES) {
          trace.splice(0, trace.length - MAX_SCOPE_TRACE_ENTRIES)
        }

        localStorage.setItem(traceKey, JSON.stringify(trace))
      }
    } catch {
      // ignore tracing errors during normal runtime
    }
  }, [onScopeIdsChange, selectedNode, selectedProgressLevelId])

  

  

  const renderMultiSelectInspector = () => {
    if (!(!selectedNode && Array.isArray(selectedNodeIds) && selectedNodeIds.length > 1)) {
      return null
    }

    const count = selectedNodeIds.length

    const allNodes = []
    const queue = [...(roadmapData?.children ?? [])]
    while (queue.length > 0) {
      const node = queue.shift()
      allNodes.push(node)
      queue.push(...(node.children ?? []))
    }

    const selectedNodes = selectedNodeIds.map((id) => allNodes.find((node) => node.id === id)).filter(Boolean)
    const segmentData = (roadmapData?.segments ?? []).map((segment) => ({ value: segment.id, label: segment.label }))
    const parentData = allNodes
      .filter((node) => !selectedNodeIds.includes(node.id))
      .map((node) => ({ value: node.id, label: node.shortName ? `${node.label} (${node.shortName})` : node.label }))
    const visibleNames = selectedNodes.slice(0, 3).map((node) => node.label).filter(Boolean).join(', ')
    const hasMore = selectedNodes.length > 3
    const headerNames = hasMore ? `${visibleNames} (...)` : visibleNames

    return (
      <Paper className="skill-panel skill-panel--inspector" radius={0} shadow="none">
        <div className="skill-panel__header">
          <div>
            <Text className="skill-panel__eyebrow">Inspector</Text>
            <Text className="skill-panel__title skill-panel__title--large">{`${count} selected${headerNames ? ' - ' + headerNames : ''}`}</Text>
          </div>
          <div className="skill-panel__header-actions">
            <ActionIcon variant="subtle" color="gray" onClick={() => { /* noop: parent closes */ }} aria-label="Close inspector">
              ✕
            </ActionIcon>
          </div>
        </div>
        <div className="skill-panel__body skill-panel__body--scrollable">
          <Stack gap="md">
            <div className="multi-inspector__selected-row" style={{ display: 'flex', gap: 8, overflowX: 'auto', paddingBottom: 6 }}>
              {selectedNodes.map((node) => (
                <Badge
                  key={node.id}
                  variant="filled"
                  radius="sm"
                  sx={{ cursor: onFocusNode ? 'pointer' : 'default', padding: '6px 10px', whiteSpace: 'nowrap' }}
                  onClick={() => onFocusNode?.(node.id)}
                >
                  {node.shortName ?? node.label}
                </Badge>
              ))}
            </div>

            <Select
              label="Segment (for all)"
              data={segmentData}
              onChange={(value) => value && onSegmentChange(value)}
              allowDeselect={false}
              classNames={{ input: 'mantine-dark-input', label: 'mantine-dark-label', dropdown: 'mantine-dark-dropdown', option: 'mantine-dark-option' }}
              comboboxProps={{ withinPortal: true, zIndex: 450 }}
            />

            <Select
              label="Parent (for all)"
              data={parentData}
              onChange={(value) => value && onParentChange(value)}
              allowDeselect={false}
              classNames={{ input: 'mantine-dark-input', label: 'mantine-dark-label', dropdown: 'mantine-dark-dropdown', option: 'mantine-dark-option' }}
              comboboxProps={{ withinPortal: true, zIndex: 450 }}
            />

            <Select
              label="Status (for all)"
              data={BULK_STATUS_OPTIONS}
              onChange={(value) => value && onStatusChange(value)}
              allowDeselect={false}
              classNames={{ input: 'mantine-dark-input', label: 'mantine-dark-label', dropdown: 'mantine-dark-dropdown', option: 'mantine-dark-option' }}
              comboboxProps={{ withinPortal: true, zIndex: 450 }}
            />

            <Text size="sm" c="dimmed">
              Use the list view filter bar to multi-select levels and assign named open-point tags in bulk.
            </Text>

            <MultiSelect
              label="Scopes (for all)"
              data={(scopeOptions ?? []).map((scope) => ({ value: scope.value, label: scope.label }))}
              onChange={(values) => onScopeIdsChange(values)}
              searchable
              clearable
              classNames={{ input: 'mantine-dark-input', label: 'mantine-dark-label', dropdown: 'mantine-dark-dropdown', option: 'mantine-dark-option', pill: 'mantine-dark-pill' }}
              comboboxProps={{ withinPortal: true, zIndex: 450 }}
            />

            <Button variant="light" onClick={() => onSelectAllNodes?.()}>Select all skills</Button>

            <Divider />

            <div className="skill-panel__danger-zone">
              <Text className="skill-panel__danger-title">Delete (for selected nodes)</Text>
              <Button variant="default" onClick={onDeleteNodeOnly}>Delete skill (for all)</Button>
              <Button color="red" variant="outline" onClick={onDeleteNodeBranch}>Delete branch (for all)</Button>
            </div>
          </Stack>
        </div>
      </Paper>
    )
  }

  const multiSelectInspector = renderMultiSelectInspector()

  const nodeLevels = selectedNode && Array.isArray(selectedNode.levels) && selectedNode.levels.length > 0
    ? selectedNode.levels.map((level, index) => {
      const rawLabel = level.label ?? getDefaultLevelLabel(index)
      return {
        id: level.id,
        label: rawLabel,
        customLabel: getExplicitLevelLabel(rawLabel),
        displayLabel: getLevelDisplayLabel(rawLabel, index),
        ordinalLabel: getDefaultLevelLabel(index),
        status: getLevelStatus(level, selectedReleaseId),
        releaseNote: level.releaseNote ?? '',
        openPointsLabel: String(level.openPointsLabel ?? ''),
        scopeIds: Array.isArray(level.scopeIds) ? level.scopeIds : [],
        hasOpenPoints: Boolean(level.hasOpenPoints),
        additionalDependencyLevelIds: Array.isArray(level.additionalDependencyLevelIds) ? level.additionalDependencyLevelIds : [],
        effort: level.effort ?? null,
        benefit: level.benefit ?? null,
      }
    })
    : [{ id: 'level-1', label: 'Level 1', customLabel: '', displayLabel: 'Level 1', ordinalLabel: 'Level 1', status: getLevelStatus({ statuses: {}, status: selectedNode?.status }, selectedReleaseId), releaseNote: '', openPointsLabel: '', hasOpenPoints: false, scopeIds: [], additionalDependencyLevelIds: [] }]

  const scopeSelectData = (scopeOptions ?? []).map((scope) => ({
    value: scope.value,
    label: scope.label,
    color: scope.color ?? null,
  }))

  const handleCreateScope = () => {
    const result = onCreateScope?.(scopeDraft)

    if (!result?.ok) {
      setScopeError(result?.error ?? 'Scope could not be created.')
      return
    }

    setScopeError(null)
    setScopeDraft('')
  }

  const handleCreateSegment = () => {
    const result = onCreateSegment?.(segmentDraft)

    if (!result?.ok && result !== undefined) {
      setSegmentError(result?.error ?? 'Segment could not be created.')
      return
    }

    setSegmentError(null)
    setSegmentDraft('')
  }

  const handleStartRenameSegment = (segmentId, label) => {
    setSegmentError(null)
    setEditingSegmentId(segmentId)
    setEditingSegmentLabel(label)
  }

  const handleRenameSegment = () => {
    if (!editingSegmentId) {
      return
    }

    const result = onRenameSegment?.(editingSegmentId, editingSegmentLabel)
    if (!result?.ok && result !== undefined) {
      setSegmentError(result?.error ?? 'Segment could not be renamed.')
      return
    }

    setSegmentError(null)
    setEditingSegmentId(null)
    setEditingSegmentLabel('')
  }

  const handleDeleteSegment = (segmentId) => {
    const result = onDeleteSegment?.(segmentId)
    if (!result?.ok && result !== undefined) {
      setSegmentError(result?.error ?? 'Segment could not be deleted.')
      return
    }

    setSegmentError(null)
    if (editingSegmentId === segmentId) {
      setEditingSegmentId(null)
      setEditingSegmentLabel('')
    }
  }

  const handleStartRenameScope = (scopeId, label) => {
    setScopeError(null)
    setEditingScopeId(scopeId)
    setEditingScopeLabel(label)
    setColorPickerOpenId(null)
  }

  const handleRenameScope = () => {
    if (!editingScopeId) {
      return
    }

    const result = onRenameScope?.(editingScopeId, editingScopeLabel)
    if (!result?.ok) {
      setScopeError(result?.error ?? 'Scope could not be renamed.')
      return
    }

    setScopeError(null)
    setEditingScopeId(null)
    setEditingScopeLabel('')
  }

  const handleDeleteScope = (scopeId) => {
    const result = onDeleteScope?.(scopeId)
    if (!result?.ok) {
      setScopeError(result?.error ?? 'Scope could not be deleted.')
      return
    }

    setScopeError(null)
    if (editingScopeId === scopeId) {
      setEditingScopeId(null)
      setEditingScopeLabel('')
    }
    if (colorPickerOpenId === scopeId) {
      setColorPickerOpenId(null)
    }
  }

  const selectedSegmentKey = selectedNode?.segmentId ?? UNASSIGNED_SEGMENT_ID
  const blockedRingHint = levelOptions.find((option) => !option.isAllowed)?.reasons?.[0] ?? null

  // Collect all short names in the tree except the current node for duplicate check
  const otherShortNames = useMemo(() => {
    const names = new Set()
    const queue = [...(roadmapData?.children ?? [])]
    while (queue.length > 0) {
      const node = queue.shift()
      if (node.id !== selectedNode?.id) {
        const sn = String(node.shortName ?? '').trim().toLowerCase()
        if (sn) names.add(sn)
      }
      queue.push(...(node.children ?? []))
    }
    return names
  }, [roadmapData, selectedNode?.id])

  const shortNameDuplicateWarning = useMemo(() => {
    const draft = String(shortNameDraft ?? '').trim().toLowerCase()
    if (!draft) return null
    return otherShortNames.has(draft) ? 'This shortname is already used by another node.' : null
  }, [shortNameDraft, otherShortNames])

  const openPointTagOptions = useMemo(() => {
    const tags = new Set()
    const queue = [...(roadmapData?.children ?? [])]
    while (queue.length > 0) {
      const node = queue.shift()
      for (const level of node.levels ?? []) {
        const label = String(level?.openPointsLabel ?? '').trim()
        if (label) {
          tags.add(label)
        }
      }
      queue.push(...(node.children ?? []))
    }
    return Array.from(tags)
  }, [roadmapData])
  const ringData = levelOptions.map((option) => ({
    value: String(option.value),
    label: `Ring ${option.value}`,
    disabled: !option.isAllowed,
  }))
  const segmentData = (segmentOptions ?? []).map((option) => ({
    value: option.id,
    label: option.label,
  }))
  const parentData = (parentOptions ?? []).map((option) => ({
    value: option.id,
    label: option.shortName ? `${option.label} (${option.shortName})` : option.label,
    disabled: !option.isAllowed,
  }))
  const selectedParentKey = selectedParentId ?? '__root__'

  const renderDependencyGroup = (title, entries) => (
    <Stack gap={6} style={{ flex: 1, minWidth: 0 }}>
      <Text size="sm" fw={600}>{`${title} (${entries.length})`}</Text>

      {entries.length > 0 ? (
        <>
          <Stack gap={4}>
            {entries.map((entry) => (
              <button
                key={`${title}-row-${entry.id}`}
                type="button"
                onClick={() => onFocusNode?.(entry.id)}
                style={{
                  textAlign: 'left',
                  background: 'rgba(15, 23, 42, 0.45)',
                  border: '1px solid rgba(148, 163, 184, 0.25)',
                  borderRadius: 8,
                  padding: '8px 10px',
                  color: '#e2e8f0',
                  cursor: 'pointer',
                }}
              >
                <Text size="sm" fw={500}>
                  {entry.shortName ? `${entry.shortName} - ${entry.label}` : entry.label}
                </Text>
                {(entry.scopes ?? []).length > 0 && (
                  <Group gap={6} mt={6} wrap="wrap">
                    {entry.scopes.slice(0, MAX_SCOPE_CHIPS_PER_ENTRY).map((scope) => (
                      <span
                        key={`${entry.id}-scope-${scope.id}`}
                        style={scope.color
                          ? {
                              ...dependencyScopeChipStyle,
                              borderColor: scope.color,
                              color: scope.color,
                            }
                          : dependencyScopeChipStyle}
                      >
                        {scope.label}
                      </span>
                    ))}
                    {entry.scopes.length > MAX_SCOPE_CHIPS_PER_ENTRY && (
                      <span
                        style={dependencyScopeChipStyle}
                      >
                        +{entry.scopes.length - MAX_SCOPE_CHIPS_PER_ENTRY}
                      </span>
                    )}
                  </Group>
                )}
              </button>
            ))}
          </Stack>
        </>
      ) : (
        <Text size="sm" c="dimmed">No dependencies</Text>
      )}
    </Stack>
  )

  const [activeTab, setActiveTab] = useState('properties')
  const [openPointTagDraft, setOpenPointTagDraft] = useState('')
  const lastSyncedProgressLevelIdRef = useRef(null)

  const applyOpenPointTag = useCallback((levelId, value) => {
    const nextTag = String(value ?? '').trim()
    if (!nextTag) {
      return
    }

    if (typeof onOpenPointTagChange === 'function') {
      onOpenPointTagChange(nextTag, levelId)
    } else {
      onOpenPointsChange?.(true, levelId)
      onOpenPointsLabelChange?.(nextTag, levelId)
    }

    setOpenPointTagDraft('')
  }, [onOpenPointTagChange, onOpenPointsChange, onOpenPointsLabelChange])

  const resetLevelDragState = useCallback(() => {
    setDraggedLevelId(null)
    setDragOverLevelId(null)
    setDragInsertPosition(null)
  }, [])

  const handleLevelDragStart = useCallback((levelId) => (event) => {
    if (nodeLevels.length <= 1) {
      return
    }

    setDraggedLevelId(levelId)
    setDragOverLevelId(null)
    setDragInsertPosition(null)

    if (event.dataTransfer) {
      event.dataTransfer.effectAllowed = 'move'
      try {
        event.dataTransfer.setData('text/plain', levelId)
      } catch {
        // Ignore browsers/environments that restrict drag payloads.
      }
    }
  }, [nodeLevels])

  const handleLevelDragOver = useCallback((levelId) => (event) => {
    const sourceId = draggedLevelId || event.dataTransfer?.getData('text/plain')
    if (!sourceId || sourceId === levelId) {
      return
    }

    event.preventDefault()
    if (event.dataTransfer) {
      event.dataTransfer.dropEffect = 'move'
    }

    const insertPosition = getLevelDragInsertPosition(sourceId, levelId, event, nodeLevels)
    if (!insertPosition) {
      setDragOverLevelId(null)
      setDragInsertPosition(null)
      return
    }

    setDragOverLevelId(levelId)
    setDragInsertPosition(insertPosition)
  }, [draggedLevelId, nodeLevels])

  const handleLevelDrop = useCallback((levelId) => (event) => {
    event.preventDefault()
    const sourceId = draggedLevelId || event.dataTransfer?.getData('text/plain')
    const insertPosition = getLevelDragInsertPosition(sourceId, levelId, event, nodeLevels)
    resetLevelDragState()

    if (!sourceId || sourceId === levelId || !insertPosition) {
      return
    }

    onReorderProgressLevel?.(sourceId, levelId, insertPosition)
  }, [draggedLevelId, nodeLevels, onReorderProgressLevel, resetLevelDragState])

  useEffect(() => {
    setActiveTab('properties')
    lastSyncedProgressLevelIdRef.current = null
    resetLevelDragState()
  }, [resetLevelDragState, selectedNode?.id])

  useEffect(() => {
    if (!selectedProgressLevelId || selectedProgressLevelId === lastSyncedProgressLevelIdRef.current) {
      return
    }

    const levelForTab = nodeLevels.find((level) => level.id === selectedProgressLevelId)
    if (!levelForTab) {
      return
    }

    lastSyncedProgressLevelIdRef.current = selectedProgressLevelId
    setActiveTab(selectedProgressLevelId)

    const nextReleaseNote = levelForTab.releaseNote ?? ''
    releaseNoteDraftRef.current = nextReleaseNote
    committedReleaseNoteRef.current = nextReleaseNote
    setReleaseNoteDraft(nextReleaseNote)
  }, [nodeLevels, selectedProgressLevelId])

  const handleTabChange = useCallback((newValue) => {
    if (!newValue) return
    commitCurrentDrafts(false, 'tab-switch')
    setActiveTab(newValue)
    const levelForTab = nodeLevels.find((l) => l.id === newValue)
    if (levelForTab) {
      const nextReleaseNote = levelForTab.releaseNote ?? ''
      releaseNoteDraftRef.current = nextReleaseNote
      committedReleaseNoteRef.current = nextReleaseNote
      setReleaseNoteDraft(nextReleaseNote)
      lastSyncedProgressLevelIdRef.current = newValue
      onSelectProgressLevel?.(newValue)
    }
  }, [commitCurrentDrafts, nodeLevels, onSelectProgressLevel])

  if (!selectedNode) {
    return multiSelectInspector
  }

  return (
    <Paper
      className="skill-panel skill-panel--inspector"
      radius={0}
      shadow="none"
      data-selected-node-id={selectedNode.id}
    >
      {/* ── Header: node name in title ── */}
      <div className="skill-panel__header">
        <div style={{ flex: 1, minWidth: 0 }}>
          <Text className="skill-panel__eyebrow">Inspector</Text>

          {isTitleEditing ? (
            <div className="skill-panel__title-editor">
              <div className="skill-panel__title-editor-fields">
                <TextInput
                  ref={headerNameInputRef}
                  aria-label="Node name"
                  placeholder="Node name"
                  value={nameDraft}
                  onChange={(event) => {
                    const nextValue = event.currentTarget.value
                    const currentLabel = nameDraftRef.current
                    nameDraftRef.current = nextValue
                    setNameDraft(nextValue)
                    syncGeneratedShortNameDraft(nextValue, currentLabel)
                  }}
                  onKeyDown={handleTitleEditKeyDown}
                  classNames={{ input: 'mantine-dark-input' }}
                />
                <TextInput
                  aria-label="Node shortname"
                  placeholder="Shortname"
                  value={shortNameDraft}
                  onChange={(event) => {
                    const nextValue = event.currentTarget.value
                    shortNameDraftRef.current = nextValue
                    setShortNameDraft(nextValue)
                  }}
                  onKeyDown={handleTitleEditKeyDown}
                  error={shortNameDuplicateWarning ?? undefined}
                  rightSectionPointerEvents="all"
                  rightSectionWidth={34}
                  rightSection={(
                    <ActionIcon
                      size="sm"
                      variant="subtle"
                      color="gray"
                      aria-label="Generate shortname"
                      onMouseDown={(event) => event.preventDefault()}
                      onClick={handleGenerateShortName}
                    >
                      <TablerRefreshIcon size={14} />
                    </ActionIcon>
                  )}
                  classNames={{ input: 'mantine-dark-input' }}
                />
              </div>
              <div className="skill-panel__title-editor-actions">
                <ActionIcon variant="light" color="teal" onClick={handleSaveTitleEdit} aria-label="Save node title">
                  ✓
                </ActionIcon>
                <ActionIcon variant="light" color="gray" onClick={handleCancelTitleEdit} aria-label="Cancel node title edit">
                  ✕
                </ActionIcon>
              </div>
            </div>
          ) : (
            <button
              type="button"
              className="skill-panel__title-trigger"
              onDoubleClick={handleStartTitleEdit}
              aria-label="Double-click to rename node title"
              title="Double-click to rename node title"
            >
              <Text className="skill-panel__title skill-panel__title--node">
                {selectedNode.shortName
                  ? `${selectedNode.label} (${selectedNode.shortName})`
                  : selectedNode.label}
              </Text>
            </button>
          )}
        </div>
        <div className="skill-panel__header-actions">
          <ActionIcon variant="subtle" color="gray" onClick={() => { commitCurrentDrafts(false, 'explicit'); onClose?.() }} aria-label="Close inspector">
            ✕
          </ActionIcon>
        </div>
      </div>

      {/* ── Tab container ── */}
      <div className="skill-panel__tab-container">
        <Tabs
          value={activeTab}
          onChange={handleTabChange}
          classNames={{
            root: 'skill-panel__tabs-root',
            panel: 'skill-panel__tab-panel',
            list: 'skill-panel__tabs-list',
          }}
        >
          <Tabs.List>
            <Tabs.Tab value="properties">Properties</Tabs.Tab>

            {nodeLevels.map((level, index) => (
              <Tabs.Tab
                key={level.id}
                value={level.id}
                draggable={nodeLevels.length > 1}
                onDragStart={handleLevelDragStart(level.id)}
                onDragOver={handleLevelDragOver(level.id)}
                onDrop={handleLevelDrop(level.id)}
                onDragEnd={resetLevelDragState}
                className={`skill-panel__level-tab${draggedLevelId === level.id ? ' skill-panel__level-tab--dragging' : ''}${dragOverLevelId === level.id && draggedLevelId !== level.id ? ' skill-panel__level-tab--drop-target' : ''}${dragOverLevelId === level.id && draggedLevelId !== level.id && dragInsertPosition === 'before' ? ' skill-panel__level-tab--drop-before' : ''}${dragOverLevelId === level.id && draggedLevelId !== level.id && dragInsertPosition === 'after' ? ' skill-panel__level-tab--drop-after' : ''}`}
                title={nodeLevels.length > 1 ? `${level.displayLabel} · Drag to reorder` : level.displayLabel}
                aria-label={level.displayLabel}
              >
                <span className="skill-panel__level-tab-index">{`L${index + 1}`}</span>
                {level.customLabel ? <span className="skill-panel__level-tab-name">{truncateLevelTabName(level.customLabel)}</span> : null}
                {level.hasOpenPoints ? (
                  <span aria-label="Open points" title="Open points" style={{ color: '#ef4444', marginLeft: 6, fontSize: '0.8rem' }}>●</span>
                ) : null}
              </Tabs.Tab>
            ))}

            <ActionIcon
              size="sm"
              variant="filled"
              color="cyan"
              onClick={onAddProgressLevel}
              aria-label="Add level"
              ml={4}
              style={{ alignSelf: 'center' }}
            >
              +
            </ActionIcon>
          </Tabs.List>

          {/* ── Eigenschaften Tab ── */}
          <Tabs.Panel value="properties">
            <div className="skill-panel__tab-scroll">
              <Stack gap="xl">

                {/* Gruppe 1: Bezeichnung */}
                <Stack gap="sm">
                  <Text size="xs" fw={600} tt="uppercase" c="dimmed" lts="0.1em">Bezeichnung</Text>
                  <Textarea
                    label="Name"
                    placeholder="Enter skill name …"
                    value={nameDraft}
                    onChange={(event) => {
                      const nextValue = event.currentTarget.value
                      const currentLabel = nameDraftRef.current
                      nameDraftRef.current = nextValue
                      setNameDraft(nextValue)
                      syncGeneratedShortNameDraft(nextValue, currentLabel)
                    }}
                    onBlur={() => commitCurrentDrafts(true, 'explicit')}
                    minRows={3}
                    maxRows={8}
                    autosize
                    classNames={{ input: 'mantine-dark-input', label: 'mantine-dark-label' }}
                  />
                  <TextInput
                    label="Shortname"
                    placeholder="e.g. API"
                    value={shortNameDraft}
                    onChange={(event) => {
                      const nextValue = event.currentTarget.value
                      shortNameDraftRef.current = nextValue
                      setShortNameDraft(nextValue)
                    }}
                    onBlur={() => commitCurrentDrafts(true, 'explicit')}
                    error={shortNameDuplicateWarning}
                    rightSectionPointerEvents="all"
                    rightSectionWidth={34}
                    rightSection={(
                      <ActionIcon
                        size="sm"
                        variant="subtle"
                        color="gray"
                        aria-label="Generate shortname"
                        onMouseDown={(event) => event.preventDefault()}
                        onClick={handleGenerateShortName}
                      >
                        <TablerRefreshIcon size={14} />
                      </ActionIcon>
                    )}
                    classNames={{ input: 'mantine-dark-input', label: 'mantine-dark-label', description: 'mantine-dark-description' }}
                  />
                </Stack>

                {/* Gruppe 2: Einordnung */}
                <Stack gap="sm">
                  <Text size="xs" fw={600} tt="uppercase" c="dimmed" lts="0.1em">Einordnung</Text>

                  {parentOptions && parentOptions.length > 0 && (
                    <Select
                      label="Parent"
                      data={parentData}
                      value={selectedParentKey}
                      onChange={(value) => value && onParentChange(value)}
                      allowDeselect={false}
                      classNames={{
                        input: 'mantine-dark-input',
                        label: 'mantine-dark-label',
                        dropdown: 'mantine-dark-dropdown',
                        option: 'mantine-dark-option',
                      }}
                      comboboxProps={{ withinPortal: true, zIndex: 450 }}
                    />
                  )}

                  {segmentOptions && segmentOptions.length > 0 && (
                    <>
                      <Group gap="xs" align="center" wrap="nowrap">
                        <Select
                          label="Segment"
                          data={segmentData}
                          value={selectedSegmentKey}
                          onChange={(value) => value && onSegmentChange(value)}
                          allowDeselect={false}
                          flex={1}
                          classNames={{
                            input: 'mantine-dark-input',
                            label: 'mantine-dark-label',
                            description: 'mantine-dark-description',
                            dropdown: 'mantine-dark-dropdown',
                            option: 'mantine-dark-option',
                          }}
                          comboboxProps={{ withinPortal: true, zIndex: 450 }}
                        />
                        <Tooltip label="Manage segments">
                          <ActionIcon variant="light" color="gray" onClick={() => setSegmentManagerOpen((open) => !open)} aria-label="Manage segments">
                            <IconPercentage20 size={15} />
                          </ActionIcon>
                        </Tooltip>
                      </Group>

                      <div className={`skill-panel__segment-accordion ${segmentManagerOpen ? 'skill-panel__segment-accordion--open' : ''}`}>
                        <Stack gap="sm">
                          <Group align="flex-end" wrap="nowrap">
                            <TextInput
                              label="Manage segments"
                              placeholder="New segment"
                              value={segmentDraft}
                              onChange={(event) => setSegmentDraft(event.currentTarget.value)}
                              style={{ flex: 1 }}
                              classNames={{ input: 'mantine-dark-input', label: 'mantine-dark-label' }}
                            />
                            <Tooltip label="Add segment">
                              <ActionIcon variant="light" color="cyan" size="lg" onClick={handleCreateSegment} aria-label="Add segment">
                                <TablerCirclePlusIcon size={20} />
                              </ActionIcon>
                            </Tooltip>
                          </Group>
                          <Divider />
                          <Stack gap={8}>
                            {(segmentData ?? []).length === 0 && <Text size="sm" c="dimmed">Noch keine Segmente vorhanden.</Text>}
                            {(segmentData ?? []).map((segment) => (
                              <Paper key={segment.value} withBorder radius="md" p="xs">
                                {editingSegmentId === segment.value ? (
                                  <Stack gap={8}>
                                    <TextInput value={editingSegmentLabel} onChange={(event) => setEditingSegmentLabel(event.currentTarget.value)} classNames={{ input: 'mantine-dark-input' }} />
                                    <Group justify="space-between">
                                      <Button size="xs" variant="light" onClick={() => { setEditingSegmentId(null); setEditingSegmentLabel('') }}>Cancel</Button>
                                      <Button size="xs" onClick={handleRenameSegment}>Save</Button>
                                    </Group>
                                  </Stack>
                                ) : (
                                  <Group justify="space-between" wrap="nowrap">
                                    <Text size="sm" truncate>{segment.label}</Text>
                                    <Group gap={6} wrap="nowrap">
                                      <ActionIcon size="sm" variant="subtle" color="gray" onClick={() => handleStartRenameSegment(segment.value, segment.label)} aria-label="Rename segment">✎</ActionIcon>
                                      <ActionIcon size="sm" variant="subtle" color="red" onClick={() => handleDeleteSegment(segment.value)} aria-label="Delete segment">✕</ActionIcon>
                                    </Group>
                                  </Group>
                                )}
                              </Paper>
                            ))}
                            {segmentError && <Alert color="red" variant="light">{segmentError}</Alert>}
                          </Stack>
                        </Stack>
                      </div>
                    </>
                  )}

                  <Select
                    label="Ring"
                    data={ringData}
                    value={String(currentLevel)}
                    onChange={(value) => value && onLevelChange(parseInt(value, 10))}
                    allowDeselect={false}
                    description={blockedRingHint ?? undefined}
                    classNames={{
                      input: 'mantine-dark-input',
                      label: 'mantine-dark-label',
                      description: 'mantine-dark-description',
                      dropdown: 'mantine-dark-dropdown',
                      option: 'mantine-dark-option',
                    }}
                    comboboxProps={{ withinPortal: true, zIndex: 450 }}
                  />

                  <Paper
                    p="md"
                    radius="md"
                    withBorder
                    style={{
                      marginTop: 10,
                      background: 'linear-gradient(180deg, rgba(8, 47, 73, 0.24) 0%, rgba(15, 23, 42, 0.52) 100%)',
                      borderColor: 'rgba(56, 189, 248, 0.28)',
                    }}
                  >
                    <Stack gap="sm">
                      <Text size="xs" fw={700} tt="uppercase" c="cyan.2" lts="0.11em">Dependencies</Text>
                      <Group align="flex-start" grow>
                        {renderDependencyGroup('Requires', dependencyRequires)}
                        {renderDependencyGroup('Enables', dependencyEnables)}
                      </Group>
                    </Stack>
                  </Paper>
                </Stack>

              </Stack>
            </div>

            <div className="skill-panel__tab-bottom-bar">
              <Divider mb="sm" />
              <Stack gap="sm">
                <Button variant="light" onClick={() => onSelectAllNodes?.()}>Select all skills</Button>
                <Group gap="sm" grow>
                  <Button variant="default" onClick={onDeleteNodeOnly}>Delete skill</Button>
                  <Button color="red" variant="outline" onClick={onDeleteNodeBranch}>Delete branch</Button>
                </Group>
              </Stack>
            </div>
          </Tabs.Panel>

          {/* ── Level Tabs ── */}
          {nodeLevels.map((level) => (
            <Tabs.Panel key={level.id} value={level.id}>
              <div className="skill-panel__tab-scroll skill-panel__tab-scroll--level">
                <Stack gap="md" style={{ flexShrink: 0 }}>
                  <Group justify="space-between" align="center" wrap="nowrap">
                    <Group gap="xs" align="center" wrap="nowrap">
                      <Badge variant="light" color="cyan">{level.ordinalLabel}</Badge>
                      {nodeLevels.length > 1 && (
                        <Text size="xs" c="dimmed">Tab position defines the level number.</Text>
                      )}
                    </Group>
                    {level.hasOpenPoints ? (
                      <ActionIcon
                        size="sm"
                        variant="light"
                        color="teal"
                        aria-label="Mark open point done"
                        title="Mark open point done"
                        onClick={() => onOpenPointsChange?.(false, level.id)}
                      >
                        <IconCheck size={16} />
                      </ActionIcon>
                    ) : (
                      <Menu shadow="md" width={240} position="bottom-end" closeOnItemClick={false}>
                        <Menu.Target>
                          <ActionIcon
                            size="sm"
                            variant="light"
                            color="red"
                            aria-label="Add open point"
                            title="Add open point"
                          >
                            <IconChecklist size={16} />
                          </ActionIcon>
                        </Menu.Target>
                        <Menu.Dropdown>
                          <Menu.Label>Open point tag</Menu.Label>
                          {openPointTagOptions.length > 0 ? openPointTagOptions.map((tag) => (
                            <Menu.Item key={`${level.id}-${tag}`} onClick={() => applyOpenPointTag(level.id, tag)}>
                              {tag}
                            </Menu.Item>
                          )) : (
                            <Text size="xs" c="dimmed" px="sm" py={4}>No tags yet</Text>
                          )}
                          <Menu.Divider />
                          <div style={{ padding: '0.45rem', display: 'grid', gap: '0.4rem' }}>
                            <TextInput
                              size="xs"
                              value={openPointTagDraft}
                              onChange={(event) => setOpenPointTagDraft(event.currentTarget.value)}
                              placeholder="Add tag"
                              aria-label="Add new tag"
                              onKeyDown={(event) => {
                                if (event.key === 'Enter') {
                                  event.preventDefault()
                                  applyOpenPointTag(level.id, openPointTagDraft)
                                }
                              }}
                            />
                            <Button
                              size="xs"
                              color="red"
                              onClick={() => applyOpenPointTag(level.id, openPointTagDraft)}
                              disabled={!String(openPointTagDraft ?? '').trim()}
                            >
                              Add tag
                            </Button>
                          </div>
                        </Menu.Dropdown>
                      </Menu>
                    )}
                  </Group>

                  <TextInput
                    key={`level-name-${selectedNode?.id ?? 'node'}-${level.id}-${level.label}`}
                    label="Level Name"
                    placeholder="e.g. Foundation"
                    defaultValue={levelLabelDrafts[level.id] ?? level.customLabel}
                    onChange={(event) => {
                      const nextValue = event.currentTarget.value
                      levelLabelDraftsRef.current = {
                        ...levelLabelDraftsRef.current,
                        [level.id]: nextValue,
                      }
                    }}
                    onBlur={(event) => {
                      const nextValue = event.currentTarget.value
                      levelLabelDraftsRef.current = {
                        ...levelLabelDraftsRef.current,
                        [level.id]: nextValue,
                      }
                      setLevelLabelDrafts((prev) => ({
                        ...prev,
                        [level.id]: nextValue,
                      }))
                      onLevelLabelChange?.(nextValue, level.id)
                    }}
                    classNames={{ input: 'mantine-dark-input', label: 'mantine-dark-label' }}
                  />

                  <div>
                    <Text className="mantine-dark-label" size="sm" mb={6}>Status</Text>
                    <SegmentedControl
                      fullWidth
                      size="xs"
                      value={level.status}
                      onChange={(value) => value && onStatusChange(value)}
                      data={STATUS_OPTIONS}
                      classNames={{
                        root: 'skill-panel__status-segmented',
                        control: 'skill-panel__status-segmented-control',
                        label: 'skill-panel__status-segmented-label',
                        indicator: 'skill-panel__status-segmented-indicator',
                      }}
                    />
                  </div>


                  <div>
                    <Text className="mantine-dark-label" size="sm" mb={6}>Effort</Text>
                    <DiscreteInspectorSlider
                      sizes={EFFORT_SIZES}
                      labels={EFFORT_SIZE_LABELS}
                      value={level.effort?.size ?? 'unclear'}
                      marks={EFFORT_MARKS}
                      onCommit={(size) => onEffortChange?.({ size, customPoints: level.effort?.customPoints ?? null })}
                    />
                    {level.effort?.size === 'custom' && (
                      <NumberInput
                        mt={6}
                        label="Story Points (Custom)"
                        placeholder="e.g. 7"
                        value={level.effort?.customPoints ?? ''}
                        onChange={(val) => onEffortChange?.({ size: 'custom', customPoints: val === '' ? null : Number(val) })}
                        min={0}
                        allowDecimal={false}
                        classNames={{ input: 'mantine-dark-input', label: 'mantine-dark-label' }}
                      />
                    )}
                  </div>

                  <div>
                    <Text className="mantine-dark-label" size="sm" mb={6}>Benefit</Text>
                    <DiscreteInspectorSlider
                      sizes={BENEFIT_SIZES}
                      labels={BENEFIT_SIZE_LABELS}
                      value={level.benefit?.size ?? 'unclear'}
                      marks={BENEFIT_MARKS}
                      onCommit={(size) => onBenefitChange?.({ size })}
                    />
                  </div>

                  <div className="skill-panel__scope-block">
                    <Group justify="space-between" align="center" mb={6}>
                      <Text className="mantine-dark-label" size="sm">Scope</Text>
                      <Tooltip label="Without assignment, the level applies to all product groups.">
                        <ActionIcon variant="subtle" color="gray" size="sm" aria-label="Scope hint">
                          <TablerInfoCircleIcon size={15} />
                        </ActionIcon>
                      </Tooltip>
                    </Group>

                    <Group gap="xs" align="center" wrap="nowrap">
                      <MultiSelect
                        data={scopeSelectData}
                        value={level.scopeIds ?? []}
                        onChange={handleScopeIdsChange}
                        placeholder="Scopes"
                        searchable
                        clearable
                        flex={1}
                        classNames={{
                          input: 'mantine-dark-input',
                          dropdown: 'mantine-dark-dropdown',
                          option: 'mantine-dark-option',
                          pill: 'mantine-dark-pill',
                        }}
                        comboboxProps={{ withinPortal: true, zIndex: 450 }}
                      />
                      <Tooltip label="Manage scopes">
                        <ActionIcon variant="light" color="gray" onClick={() => setScopeManagerOpen((open) => !open)} aria-label="Manage scopes">
                          <TablerAdjustmentsIcon size={15} />
                        </ActionIcon>
                      </Tooltip>
                    </Group>

                    <div className={`skill-panel__scope-accordion ${scopeManagerOpen ? 'skill-panel__scope-accordion--open' : ''}`}>
                      <Stack gap="sm">
                        <Group align="flex-end" wrap="nowrap">
                          <TextInput
                            label="Manage scopes"
                            placeholder="e.g. Series A"
                            value={scopeDraft}
                            onChange={(event) => setScopeDraft(event.currentTarget.value)}
                            style={{ flex: 1 }}
                            classNames={{ input: 'mantine-dark-input', label: 'mantine-dark-label' }}
                          />
                          <Tooltip label="Add scope">
                            <ActionIcon variant="light" color="cyan" size="lg" onClick={handleCreateScope} aria-label="Add scope">
                              <TablerCirclePlusIcon size={20} />
                            </ActionIcon>
                          </Tooltip>
                        </Group>
                        <Divider />
                        <Stack gap={8}>
                          {scopeSelectData.length === 0 && <Text size="sm" c="dimmed">Noch keine Scopes vorhanden.</Text>}
                          {scopeSelectData.map((scope) => (
                            <Paper key={scope.value} withBorder radius="md" p="xs">
                              {editingScopeId === scope.value ? (
                                <Stack gap={8}>
                                  <TextInput value={editingScopeLabel} onChange={(event) => setEditingScopeLabel(event.currentTarget.value)} classNames={{ input: 'mantine-dark-input' }} />
                                  <Group justify="space-between">
                                    <Button size="xs" variant="light" onClick={() => { setEditingScopeId(null); setEditingScopeLabel('') }}>Cancel</Button>
                                    <Button size="xs" onClick={handleRenameScope}>Save</Button>
                                  </Group>
                                </Stack>
                              ) : (
                                <Stack gap={6}>
                                  <Group justify="space-between" wrap="nowrap">
                                    <Group gap={8} wrap="nowrap" style={{ minWidth: 0 }}>
                                      <button
                                        type="button"
                                        aria-label="Change color"
                                        onClick={() => setColorPickerOpenId((prev) => (prev === scope.value ? null : scope.value))}
                                        style={{
                                          width: 16,
                                          height: 16,
                                          borderRadius: '50%',
                                          background: scope.color ?? 'rgba(100,116,139,0.4)',
                                          border: '1.5px solid rgba(148,163,184,0.35)',
                                          cursor: 'pointer',
                                          padding: 0,
                                          flexShrink: 0,
                                        }}
                                      />
                                      <Text size="sm" truncate>{scope.label}</Text>
                                    </Group>
                                    <Group gap={6} wrap="nowrap">
                                      <ActionIcon size="sm" variant="subtle" color="gray" onClick={() => handleStartRenameScope(scope.value, scope.label)} aria-label="Rename scope">✎</ActionIcon>
                                      <ActionIcon size="sm" variant="subtle" color="red" onClick={() => handleDeleteScope(scope.value)} aria-label="Delete scope">✕</ActionIcon>
                                    </Group>
                                  </Group>
                                  {colorPickerOpenId === scope.value && (
                                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, padding: '4px 0 2px' }}>
                                      {SCOPE_COLORS.map((color) => (
                                        <button
                                          key={color}
                                          type="button"
                                          aria-label={`Color ${color}`}
                                          onClick={() => { onSetScopeColor?.(scope.value, color); setColorPickerOpenId(null) }}
                                          style={{
                                            width: 18,
                                            height: 18,
                                            borderRadius: '50%',
                                            background: color,
                                            border: scope.color === color ? '2px solid #f8fafc' : '2px solid transparent',
                                            outline: scope.color === color ? '2px solid #06b6d4' : 'none',
                                            cursor: 'pointer',
                                            padding: 0,
                                            flexShrink: 0,
                                          }}
                                        />
                                      ))}
                                      {scope.color && (
                                        <button
                                          type="button"
                                          aria-label="Remove color"
                                          onClick={() => { onSetScopeColor?.(scope.value, null); setColorPickerOpenId(null) }}
                                          style={{
                                            width: 18,
                                            height: 18,
                                            borderRadius: '50%',
                                            background: 'transparent',
                                            border: '1.5px dashed rgba(148,163,184,0.5)',
                                            cursor: 'pointer',
                                            padding: 0,
                                            flexShrink: 0,
                                            fontSize: 9,
                                            color: '#94a3b8',
                                            display: 'flex',
                                            alignItems: 'center',
                                            justifyContent: 'center',
                                          }}
                                        >✕</button>
                                      )}
                                    </div>
                                  )}
                                </Stack>
                              )}
                            </Paper>
                          ))}
                          {scopeError && <Alert color="red" variant="light">{scopeError}</Alert>}
                        </Stack>
                      </Stack>
                    </div>
                  </div>
                </Stack>

                {(() => {
                  const levelDepOpts = (levelDependencyOptions ?? {})[level.id] ?? []
                  if (levelDepOpts.length === 0) return null
                  return (
                    <MultiSelect
                      label="Additional Dependencies"
                      data={(() => {
                        const byGroup = new Map()
                        for (const o of levelDepOpts) {
                          const g = o.group ?? ''
                          if (!byGroup.has(g)) byGroup.set(g, [])
                          byGroup.get(g).push({ value: o.value, label: o.label })
                        }
                        return [...byGroup.entries()].map(([group, items]) => ({ group, items }))
                      })()}
                      value={level.additionalDependencyLevelIds}
                      onChange={(values) => onLevelAdditionalDependenciesChange?.(level.id, values)}
                      searchable
                      clearable
                      classNames={{
                        input: 'mantine-dark-input',
                        label: 'mantine-dark-label',
                        dropdown: 'mantine-dark-dropdown',
                        option: 'mantine-dark-option',
                        pill: 'mantine-dark-pill',
                      }}
                      comboboxProps={{ withinPortal: true, zIndex: 450 }}
                    />
                  )
                })()}

                <div className="skill-panel__release-note-fill">
                  <MarkdownField
                    fill
                    label="Release Note"
                    placeholder="Describe from the customer's perspective what was delivered or comes next in this level..."
                    value={activeTab === level.id ? releaseNoteDraft : (level.releaseNote ?? '')}
                    onChange={(nextValue) => {
                      releaseNoteDraftRef.current = nextValue
                      setReleaseNoteDraft(nextValue)
                    }}
                    onBlur={() => commitCurrentDrafts(true, 'explicit')}
                  />
                </div>
              </div>

              <div className="skill-panel__tab-bottom-bar">
                <Divider mb="sm" />
                <Button
                  color="red"
                  variant="outline"
                  fullWidth
                  disabled={nodeLevels.length <= 1}
                  onClick={() => {
                    onDeleteProgressLevel(level.id)
                    setActiveTab('properties')
                  }}
                >
                  Delete level
                </Button>
              </div>
            </Tabs.Panel>
          ))}
        </Tabs>
      </div>

      {saveToast.visible && (
        <Alert color="teal" variant="light" style={{ margin: '0 1.5rem 0.75rem' }}>
          {saveToast.message}
        </Alert>
      )}

      {validationMessage && (
        <Alert color="yellow" variant="light" style={{ margin: '0 1.5rem 0.75rem' }} className="skill-panel__alert">
          {validationMessage}
        </Alert>
      )}
    </Paper>
  )
}
